# This is a basic workflow to help you get started with Actions

name: scheduled update

# Controls when the workflow will run
on:
#   schedule:
#     - cron: "*/12 * * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  render_readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: setup python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.8'
          cache: 'pip'
      
      - name: load python environment
        run: pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: render readme
        run: |
          python3.8 action__render_readme.py
      
      - name: update repository
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "justineichelberger"
          git config --global user.email "justin.g.eichelberger@gmail.com"
          git commit -m "[Automated] README updated with the most recent documentation."
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      
